// Here are all the shared preferences keys

// Keys follow this pattern: <PREFIX>_<TOOLNAME>_<NAME>
// The prefix is always "TOOL" for the tools
// The tool name is the name of the tool in uppercase and without spaces
// The name is the name of the preference in uppercase and without spaces

// Please respect this pattern when adding new preferences

const SHARED_PREFERENCES_CORE_HOMEPAGE_ISFOLDERVIEW = "CORE_HOMEPAGE_ISFOLDERVIEW";
const SHARED_PREFERENCES_CORE_HOMEPAGE_FAVORITES = "CORE_HOMEPAGE_FAVORITES";

const SHARED_PREFERENCES_TOOL_SSHCLIENT_USINGKEY = "TOOL_SSHCLIENT_USINGKEY";
const SHARED_PREFERENCES_TOOL_SSHCLIENT_HOST = "TOOL_SSHCLIENT_HOST";
const SHARED_PREFERENCES_TOOL_SSHCLIENT_USERNAME = "TOOL_SSHCLIENT_USERNAME";
const SHARED_PREFERENCES_TOOL_SSHCLIENT_PORT = "TOOL_SSHCLIENT_PORT";

const SHARED_PREFERENCES_TOOL_ROULETTE_ITEMS = "TOOL_ROULETTE_ITEMS";

const SHARED_PREFERENCES_TOOL_TEXTTOSPEECH_LANGUAGE = "TOOL_TEXTTOSPEECH_LANGUAGE";

const SHARED_PREFERENCES_TOOL_NEARBYPUBLICTRANSPORTSTOPS_FIRSTDIALOGSHOWN = "TOOL_NEARBYPUBLICTRANSPORTSTOPS_FIRSTDIALOGSHOWN";

const SHARED_PREFERENCES_TOOL_COUNTER_VALUE = "TOOL_COUNTER_VALUE";
const SHARED_PREFERENCES_TOOL_COUNTER_BUTTONS = "TOOL_COUNTER_BUTTONS";

const SHARED_PREFERENCES_TOOL_MCSERVERPING_FAVORITES = "TOOL_MCSERVERPING_FAVORITES";

const SHARED_PREFERENCES_TOOL_SPEEDOMETER_ISUSINGMPH = "TOOL_SPEEDOMETER_ISUSINGMPH";

const SHARED_PREFERENCES_TOOL_FLIPCOINS_CURRENTCOIN = "TOOL_FLIPCOINS_CURRENTCOIN";
